name: beginflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # CÃ¡c thÆ° viá»‡n hiá»‡n táº¡i
  http: ^0.13.6
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.1

  # Firebase
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2

  # SharedPreferences
  shared_preferences: ^2.3.2

  # WebSocket thay cho PhoenixSocket
  web_socket_channel: ^3.0.3

  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  phoenix_socket: 0.7.6

  # google_maps_flutter: ^2.6.0   # âŒ xÃ³a dÃ²ng nÃ y
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^10.0.0
  flutter_map_marker_popup: ^5.1.0

  # ğŸ”¹ ThÃªm Ä‘á»ƒ cháº¡y foreground service trÃªn Android
  flutter_foreground_task: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
